update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -434,25 +434,25 @@ jobs:
           name: Install dependencies
           command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
-              export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=*-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-              echo $BACKEND_IP > publicIP
-      - run:
-          name: Backend smoke test.
-          command: |
-            BACKEND_IP=$(cat publicIP)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-              echo "passed"
-              exit 0
-            else
-             echo "failed"
-              exit 1
-            fi
+      # - run:
+      #     name: Get backend url
+      #     command: |
+      #         export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=*-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+      #         echo $BACKEND_IP > publicIP
+      # - run:
+      #     name: Backend smoke test.
+      #     command: |
+      #       BACKEND_IP=$(cat publicIP)
+      #       export API_URL="http://${BACKEND_IP}:3030"
+      #       echo "${API_URL}"
+      #       if curl "${API_URL}/api/status" | grep "ok"
+      #       then
+      #         echo "passed"
+      #         exit 0
+      #       else
+      #        echo "failed"
+      #         exit 1
+      #       fi
       - run:
           name: Frontend smoke test.
           command: |
